paths:
  /pets:
    get:
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
      responses:
        "200":
          description: pet response
        "404":
          description: not found
        "400":
          description: bad request
        "500":
          description: server error
        default:
          description: unexpected error
    post:
      parameters:
        - name: pet
          in: body
          description: Pet to add to the store
          required: true
          schema:
            $ref: "#/definitions/NewPet"
      responses:
        "200":
          description: pet response
        default:
          description: unexpected error
  "/pets/{id}":
    get:
      parameters:
        - $ref: "#/parameters/PetID"
      responses:
        "200":
          description: pet response
        "404":
          description: not found
        "400":
          description: bad request
        "500":
          description: server error
        default:
          description: unexpected error
    delete:
      parameters:
        - $ref: "#/parameters/PetID"
      responses:
        "204":
          description: pet deleted
        default:
          description: unexpected error

parameters:
  PetID:
    name: id
    in: path
    description: ID of pet to fetch
    required: true
    type: integer

definitions:
  Pet:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string

  NewPet:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      tag:
        type: string

  ErrorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
      message:
        type: string
